pipeline{
 agent any
 stages{
  stage('Unit Test'){
   steps{
     echo "hello.we are inside unit test,running unit test"
   }
 }
 stage('Build'){
  steps{
     echo "We are inside build stage,building the code now"
       }
       }
 stage('Deploy'){
  steps{
    echo "We are deploying the app"
        }
      }
     }
}
